AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Tech Company Platform Backend

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 256
    Architectures:
      - x86_64
    Environment:
      Variables:
        CORS_ORIGIN: !Ref CorsOrigin
        DYNAMODB_TABLE: !Ref CompanyDataTable
        S3_BUCKET: navon-tech-images
    Tracing: Active

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  CorsOrigin:
    Type: String
    Default: "*"
    Description: CORS origin for API Gateway

Resources:
  # API Gateway with CORS
  CompanyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  # Lambda Functions
  PublicContentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/public-content/
      Handler: index.handler
      Description: Handles public content API requests
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CompanyDataTable
        - CloudWatchLogsFullAccess
      Events:
        GetContent:
          Type: Api
          Properties:
            RestApiId: !Ref CompanyApi
            Path: /api/public/{proxy+}
            Method: ANY
            Auth:
              Authorizer: NONE

  EmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/employee/
      Handler: index.handler
      Description: Handles employee intranet API requests
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CompanyDataTable
        - CloudWatchLogsFullAccess
      Events:
        EmployeeApi:
          Type: Api
          Properties:
            RestApiId: !Ref CompanyApi
            Path: /api/employee/{proxy+}
            Method: ANY

  CareerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/career/
      Handler: index.handler
      Description: Handles career and job application API requests
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CompanyDataTable
        - S3CrudPolicy:
            BucketName: navon-tech-images
        - CloudWatchLogsFullAccess
      Events:
        CareerApi:
          Type: Api
          Properties:
            RestApiId: !Ref CompanyApi
            Path: /api/careers/{proxy+}
            Method: ANY
            Auth:
              Authorizer: NONE

  JobApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/job-application/
      Handler: index.handler
      Description: Handles job application form submissions and sends emails
      MemorySize: 1024
      Timeout: 30
      Policies:
        - S3CrudPolicy:
            BucketName: navon-tech-images
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
        - CloudWatchLogsFullAccess
      Events:
        SubmitApplication:
          Type: Api
          Properties:
            RestApiId: !Ref CompanyApi
            Path: /api/apply
            Method: POST
            Auth:
              Authorizer: NONE
        SubmitApplicationOptions:
          Type: Api
          Properties:
            RestApiId: !Ref CompanyApi
            Path: /api/apply
            Method: OPTIONS
            Auth:
              Authorizer: NONE

  # DynamoDB Table with Security
  CompanyDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: TechCompanyPlatform
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  # Cognito User Pool with Security
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-users"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: given_name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: family_name
          AttributeDataType: String
          Required: false
          Mutable: true
      UserPoolTags:
        Environment: !Ref Environment
        Project: TechCompanyPlatform
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "${AWS::StackName}-client"
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30

  # CloudWatch Log Groups
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${AWS::StackName}"
      RetentionInDays: 14

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${CompanyApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"

  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"

  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolClientId"

  DynamoDBTable:
    Description: "DynamoDB Table Name"
    Value: !Ref CompanyDataTable
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDBTable"

  Region:
    Description: "AWS Region"
    Value: !Ref AWS::Region
    Export:
      Name: !Sub "${AWS::StackName}-Region"
